### ISSUE TITLE
Obtaining `bunny.npy` from `bunny.obj`

### ISSUE THREAD

**Issue by ljmartin** [glotzerlab/fresnel#106]
Hi - 
Thanks for fresnel. 

How can one get `bunny.npy` from `bunny.obj`, as in the example at https://fresnel.readthedocs.io/en/stable/examples/01-Primitives/03-Mesh-geometry.html ? 

The context is that I have a series of vertices created using the marching cubes method (I used https://github.com/ilastik/marching_cubes ). However, using these vertices the output (using fresnel) doesn't look right:

<img width="290" alt="Screen Shot 2020-03-14 at 5 35 11 pm" src="https://user-images.githubusercontent.com/8262765/76676690-29853500-661a-11ea-91b2-a8344bc49b73.png">

Can `obj` files be loaded directly?
Thanks!

edit:
the goal is to look something like this shape:
<img width="589" alt="Screen Shot 2020-03-14 at 5 38 07 pm" src="https://user-images.githubusercontent.com/8262765/76676756-9f899c00-661a-11ea-92d9-78027d90152b.png">

**Comment by ljmartin** [comment]
Closing since I realised the library I used to generate the vertices is not making triangular vertices.

**Comment by joaander** [comment]
I don't remember exactly how I made that conversion. `bunny.obj` has all triangular faces in a simple text file. I may have just written a very short parser using numpy to index into the arrays. Or I may have used a library like pywavefront: https://github.com/pywavefront/PyWavefront

In any case, direct wavefront obj reading is outside the scope of fresnel when packages like pywavefront exist. If you have non-triangular faces, you could always triangulate them for use in fresnel.
