### ISSUE TITLE
support perspective cameras with distortion

### ISSUE THREAD

**Issue by martinResearch** [glotzerlab/fresnel#107]
## Description

At the moment Fresnel supports only orthographic projection. It would be great if it could support perspective projection camera.  Ideally it would also support  [opencv's 5 parameters distortion model](https://docs.opencv.org/2.4/doc/tutorials/calib3d/camera_calibration/camera_calibration.html).
Does that sound feasible ?

**Comment by joaander** [comment]
Yes, perspective cameras are on the roadmap for Fresnel. They are needed to implement depth of field effects #30. 

What scientific visualization use-cases would need distorted projections?

**Comment by martinResearch** [comment]
distorted projections could be used in computer vision applications (not exactly scientific visualization) to generate test or training images. Maybe it would possible to provide a mechanism for the user to provide its own vectorized the camera projection implementation in numpy (or inverse projection mapping pixel coordinate to ray direction) ?

**Comment by joaander** [comment]
That is an interesting application for fresnel. We designed fresnel primarily for visualizing soft matter simulation results. I am happy to accept pull requests that enable its use in other fields as well.

I have begun work implementing the perspective camera in fresnel in #108. I added a simple pinhole camera and a thin lens model for depth of field effects. Look at `generateRay` in `Camera.h` for the implementation.

Fresnel uses Monte Carlo pixel subsampling to implement antialiasing, so unfortunately a numpy array is not a suitable solution to generalize this. The ray generation must be implemented in C++ as a function of the sample coordinates on the image plane. You could add the necessary parameters to UserCamera, Camera, and an additional mode field to CameraModels. In `generateRay`, generate the appropriate rays to implement the camera distortions.
