### ISSUE TITLE
Can't install fresnel v0.13 and freud in same conda environment?

### ISSUE THREAD

**Issue by jennyfothergill** [glotzerlab/fresnel#124]
## Description

I'm trying to install fresnel v0.13 and freud into the same environment using conda and keep getting package conflicts.

## Script

```bash
conda create -n test -c conda-forge fresnel=0.13 freud
```

## Output

Conda environment cannot solve until freud is removed

## Configuration

Platform:
- Mac 10.14.6 (18G6032)

Installation method:
- Conda package (using conda 4.9.2)

Versions:
- Python version: n/a
- Fresnel version: 0.13

**Comment by joaander** [comment]
As of this posting, `fresnel 0.13` on conda-forge is compiled against `tbb2021` and `freud` is compiled against `tbb2020`. You cannot install both tbb's at the same time. conda-forge is in the process of rebuilding all packages against `tbb2021`. Freud and HOOMD will both require some updates before they can be rebuilt against `tbb2021`.

https://github.com/conda-forge/hoomd-feedstock/pull/39
https://github.com/conda-forge/freud-feedstock/pull/35

This is not a bug in `fresnel`.
