### ISSUE TITLE
Cannot import fresnel after building an OptiX enabled version from source

### ISSUE THREAD

**Issue by FloLangenfeld** [glotzerlab/fresnel#210]
## Description

When I import fesnel, I get an ImportError about OptiX
## Script

```python
import fresnel

```

## Output

```python
ImportError: liboptix.so.6.5.0: cannot open shared object file: No such file or directory
```

## Expected output

Nothing, a no-error import

## Configuration

Platform:
- Linux
- GPU

Installation method:
- Compiled from source

Versions:
- Python version: 3.11.6
- Fresnel version: 0.13.5

## Details

To give more details, here is what I've done.

### Install the Python pre-requisites

I'm trying [pixi](https://pixi.sh/) to manage my python environnement and install my depndencies as conda packages. My pixi.toml is as below:
```
[dependencies]
python = "<3.13"
pybind11 = ">=2.11.1,<2.12"
numpy = ">=1.26.2,<1.27"
qhull = ">=2020.2,<2021"
pyside2 = ">=5.15.8,<5.16"
pytest = ">=7.4.3,<7.5"
pillow = ">=10.1.0,<10.2"
```
 
### Install the other dependencies

I'm working under an Ubuntu-based distribution. I installed the following dependencies using apt:
- cmake 3.22.1
- embree-tools 3.12.2
- libembree-dev 3.12.2
- libtbb2-dev 2020.3
- libtbb2 2020.3
- libqhull-dev 2020.2
- nvidia-cuda-toolkit 11.5.1

I then downloaded OptiX 6.5 in /opt/NVIDIA-OptiX-SDK-6.5.0-linux64 .

### Start building from source

I followed [these instructions](https://fresnel.readthedocs.io/en/v0.13.5/building.html) and issued the following commands:
```
pixi shell  # to activate the pixi environment I've created for our purpose
cd /opt
git clone --recursive https://github.com/glotzerlab/fresnel
cmake -B build/fresnel -S fresnel -DENABLE_OPTIX=ON -DOptiX_INSTALL_DIR=/opt/NVIDIA-OptiX-SDK-6.5.0-linux64 
# this command produced an error message about OptiX include not found
ccmake build/fresnel  # I manually corrected the relevant options. The cmake logs were OK - I mean ccmake produced no error
cmake --build build/fresnel
sudo cmake --install build/fresnel
```

Below are the ccmake entries about OptiX after I set them up with ccmake:
```
 OptiX_INCLUDE                    /opt/NVIDIA-OptiX-SDK-6.5.0-linux64/include
 OptiX_INSTALL_DIR                /opt/NVIDIA-OptiX-SDK-6.5.0-linux64
 optix_LIBRARY                    /opt/NVIDIA-OptiX-SDK-6.5.0-linux64/lib64/liboptix.so
 optix_prime_LIBRARY              /opt/NVIDIA-OptiX-SDK-6.5.0-linux64/lib64/liboptix_prime.so
 optixu_LIBRARY                   /opt/NVIDIA-OptiX-SDK-6.5.0-linux64/lib64/liboptixu.so
```

One last precision: the file /opt/NVIDIA-OptiX-SDK-6.5.0-linux64/lib64/liboptix.so is actually a symbolic link that points to /opt/NVIDIA-OptiX-SDK-6.5.0-linux64/lib64/liboptix.so.6.5.0. Hence, at the import time, python complains that a file that does exist does not exist...

Have you ever met this error before? Or am I wrong somewhere in the pipeline or my settings?

Any help  would be much appreciated

**Comment by joaander** [comment]
This is not a bug in fresnel. You need to set `ld.so.conf` or `$LD_LIBRARY_PATH` to include `/opt/NVIDIA-OptiX-SDK-6.5.0-linux64/lib64` in the library search directories.

Please use the [discussion board](https://github.com/glotzerlab/fresnel/discussions) for user support questions.
